version: '3.8'

services:
  ehub:
    build: .
    container_name: ehub-app
    restart: unless-stopped
    env_file:
      - .envd
    ports:
      - "8000:8000"
    networks:
      - default
      - shared-lc-network

networks:
  shared-lc-network:
    external: true